name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: publish gh pages
    runs-on: ubuntu-latest
    steps:
      - name: Install sys deps
        run: sudo apt-get install libcairo2-dev
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv
      - name: Install project python version
        run: uv python install
      - name: Install dependencies
        run: uv pip install
      - name: MkDocs Build
        run: mkdocs build
      - name: Publish gh-pages
        run: |
          git fetch -f origin gh-pages:gh-pages
          mkdocs gh-deploy
